site_name: Poetry documentation

theme:
  name: material

extra:
  version: 2.0

nav:
  - Introduction: "https://mtechnology.pl"
  - README: "README.md"

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings
